import type { BoardData } from "./types";

/** Bundled board data — map works when the API is unavailable. */
export const STATIC_BOARD: BoardData = {
  cities: [
    { name: "Vancouver", x: -123, y: 49 },
    { name: "Seattle", x: -122, y: 47 },
    { name: "Portland", x: -122, y: 45 },
    { name: "San-Francisco", x: -122, y: 37 },
    { name: "Las-Vegas", x: -115, y: 36 },
    { name: "Los-Angeles", x: -118, y: 34 },
    { name: "Phoenix", x: -112, y: 33 },
    { name: "Salt-Lake-City", x: -111, y: 40 },
    { name: "Helena", x: -112, y: 47 },
    { name: "Calgary", x: -114, y: 51 },
    { name: "Winnipeg", x: -97, y: 50 },
    { name: "Sault-St-Marie", x: -84, y: 46 },
    { name: "Duluth", x: -92, y: 46 },
    { name: "Omaha", x: -96, y: 41 },
    { name: "Denver", x: -105, y: 39 },
    { name: "Santa-Fe", x: -106, y: 35 },
    { name: "El-Paso", x: -106, y: 31 },
    { name: "Houston", x: -95, y: 29 },
    { name: "Dallas", x: -97, y: 32 },
    { name: "Oklahoma-City", x: -97, y: 35 },
    { name: "Kansas-City", x: -94, y: 39 },
    { name: "Chicago", x: -87, y: 41 },
    { name: "Saint-Louis", x: -90, y: 38 },
    { name: "Little-Rock", x: -92, y: 34 },
    { name: "New-Orleans", x: -90, y: 30 },
    { name: "Miami", x: -80, y: 25 },
    { name: "Charleston", x: -80, y: 32 },
    { name: "Atlanta", x: -84, y: 33 },
    { name: "Nashville", x: -86, y: 36 },
    { name: "Raleigh", x: -78, y: 35 },
    { name: "Washington", x: -77, y: 39 },
    { name: "Pittsburgh", x: -80, y: 40 },
    { name: "New-York", x: -74, y: 40 },
    { name: "Toronto", x: -79, y: 44 },
    { name: "Montreal", x: -73, y: 45 },
    { name: "Boston", x: -71, y: 42 },
  ],
  tracks: [
    { city_a: "Vancouver", city_b: "Seattle", route_points: 1, train_cost: 1 },
    { city_a: "Vancouver", city_b: "Calgary", route_points: 4, train_cost: 3 },
    { city_a: "Seattle", city_b: "Calgary", route_points: 7, train_cost: 4 },
    { city_a: "Seattle", city_b: "Portland", route_points: 1, train_cost: 1 },
    { city_a: "Seattle", city_b: "Helena", route_points: 15, train_cost: 6 },
    { city_a: "Portland", city_b: "Salt-Lake-City", route_points: 15, train_cost: 6 },
    { city_a: "Portland", city_b: "San-Francisco", route_points: 10, train_cost: 5 },
    { city_a: "San-Francisco", city_b: "Salt-Lake-City", route_points: 10, train_cost: 5 },
    { city_a: "San-Francisco", city_b: "Los-Angeles", route_points: 4, train_cost: 3 },
    { city_a: "Los-Angeles", city_b: "Las-Vegas", route_points: 2, train_cost: 2 },
    { city_a: "Los-Angeles", city_b: "Phoenix", route_points: 4, train_cost: 3 },
    { city_a: "Los-Angeles", city_b: "El-Paso", route_points: 15, train_cost: 6 },
    { city_a: "Las-Vegas", city_b: "Salt-Lake-City", route_points: 4, train_cost: 3 },
    { city_a: "Salt-Lake-City", city_b: "Denver", route_points: 4, train_cost: 3 },
    { city_a: "Salt-Lake-City", city_b: "Helena", route_points: 4, train_cost: 3 },
    { city_a: "Phoenix", city_b: "Denver", route_points: 10, train_cost: 5 },
    { city_a: "Phoenix", city_b: "El-Paso", route_points: 4, train_cost: 3 },
    { city_a: "Phoenix", city_b: "Santa-Fe", route_points: 4, train_cost: 3 },
    { city_a: "El-Paso", city_b: "Santa-Fe", route_points: 2, train_cost: 2 },
    { city_a: "El-Paso", city_b: "Houston", route_points: 15, train_cost: 6 },
    { city_a: "El-Paso", city_b: "Dallas", route_points: 7, train_cost: 4 },
    { city_a: "El-Paso", city_b: "Oklahoma-City", route_points: 7, train_cost: 4 },
    { city_a: "Santa-Fe", city_b: "Denver", route_points: 2, train_cost: 2 },
    { city_a: "Santa-Fe", city_b: "Oklahoma-City", route_points: 4, train_cost: 3 },
    { city_a: "Denver", city_b: "Helena", route_points: 7, train_cost: 4 },
    { city_a: "Denver", city_b: "Omaha", route_points: 7, train_cost: 4 },
    { city_a: "Denver", city_b: "Kansas-City", route_points: 7, train_cost: 4 },
    { city_a: "Denver", city_b: "Oklahoma-City", route_points: 7, train_cost: 4 },
    { city_a: "Helena", city_b: "Calgary", route_points: 7, train_cost: 4 },
    { city_a: "Helena", city_b: "Winnipeg", route_points: 7, train_cost: 4 },
    { city_a: "Helena", city_b: "Duluth", route_points: 15, train_cost: 6 },
    { city_a: "Helena", city_b: "Omaha", route_points: 10, train_cost: 5 },
    { city_a: "Calgary", city_b: "Winnipeg", route_points: 15, train_cost: 6 },
    { city_a: "Winnipeg", city_b: "Duluth", route_points: 7, train_cost: 4 },
    { city_a: "Winnipeg", city_b: "Sault-St-Marie", route_points: 15, train_cost: 6 },
    { city_a: "Duluth", city_b: "Sault-St-Marie", route_points: 4, train_cost: 3 },
    { city_a: "Duluth", city_b: "Toronto", route_points: 15, train_cost: 6 },
    { city_a: "Duluth", city_b: "Chicago", route_points: 4, train_cost: 3 },
    { city_a: "Duluth", city_b: "Omaha", route_points: 2, train_cost: 2 },
    { city_a: "Omaha", city_b: "Chicago", route_points: 7, train_cost: 4 },
    { city_a: "Omaha", city_b: "Kansas-City", route_points: 1, train_cost: 1 },
    { city_a: "Kansas-City", city_b: "Saint-Louis", route_points: 2, train_cost: 2 },
    { city_a: "Kansas-City", city_b: "Oklahoma-City", route_points: 2, train_cost: 2 },
    { city_a: "Oklahoma-City", city_b: "Little-Rock", route_points: 2, train_cost: 2 },
    { city_a: "Oklahoma-City", city_b: "Dallas", route_points: 2, train_cost: 2 },
    { city_a: "Dallas", city_b: "Houston", route_points: 1, train_cost: 1 },
    { city_a: "Dallas", city_b: "Little-Rock", route_points: 2, train_cost: 2 },
    { city_a: "Houston", city_b: "New-Orleans", route_points: 2, train_cost: 2 },
    { city_a: "New-Orleans", city_b: "Little-Rock", route_points: 4, train_cost: 3 },
    { city_a: "New-Orleans", city_b: "Atlanta", route_points: 7, train_cost: 4 },
    { city_a: "New-Orleans", city_b: "Miami", route_points: 15, train_cost: 6 },
    { city_a: "Miami", city_b: "Atlanta", route_points: 10, train_cost: 5 },
    { city_a: "Miami", city_b: "Charleston", route_points: 7, train_cost: 4 },
    { city_a: "Little-Rock", city_b: "Nashville", route_points: 4, train_cost: 3 },
    { city_a: "Little-Rock", city_b: "Saint-Louis", route_points: 2, train_cost: 2 },
    { city_a: "Saint-Louis", city_b: "Nashville", route_points: 2, train_cost: 2 },
    { city_a: "Saint-Louis", city_b: "Chicago", route_points: 2, train_cost: 2 },
    { city_a: "Saint-Louis", city_b: "Pittsburgh", route_points: 10, train_cost: 5 },
    { city_a: "Chicago", city_b: "Pittsburgh", route_points: 4, train_cost: 3 },
    { city_a: "Chicago", city_b: "Toronto", route_points: 7, train_cost: 4 },
    { city_a: "Sault-St-Marie", city_b: "Toronto", route_points: 2, train_cost: 2 },
    { city_a: "Sault-St-Marie", city_b: "Montreal", route_points: 10, train_cost: 5 },
    { city_a: "Toronto", city_b: "Montreal", route_points: 4, train_cost: 3 },
    { city_a: "Toronto", city_b: "Pittsburgh", route_points: 2, train_cost: 2 },
    { city_a: "Montreal", city_b: "Boston", route_points: 2, train_cost: 2 },
    { city_a: "Montreal", city_b: "New-York", route_points: 4, train_cost: 3 },
    { city_a: "Boston", city_b: "New-York", route_points: 2, train_cost: 2 },
    { city_a: "Pittsburgh", city_b: "New-York", route_points: 2, train_cost: 2 },
    { city_a: "Pittsburgh", city_b: "Washington", route_points: 2, train_cost: 2 },
    { city_a: "Pittsburgh", city_b: "Raleigh", route_points: 2, train_cost: 2 },
    { city_a: "New-York", city_b: "Washington", route_points: 2, train_cost: 2 },
    { city_a: "Washington", city_b: "Raleigh", route_points: 2, train_cost: 2 },
    { city_a: "Nashville", city_b: "Raleigh", route_points: 4, train_cost: 3 },
    { city_a: "Nashville", city_b: "Atlanta", route_points: 1, train_cost: 1 },
    { city_a: "Atlanta", city_b: "Raleigh", route_points: 2, train_cost: 2 },
    { city_a: "Atlanta", city_b: "Charleston", route_points: 2, train_cost: 2 },
    { city_a: "Raleigh", city_b: "Washington", route_points: 2, train_cost: 2 },
    { city_a: "Raleigh", city_b: "Charleston", route_points: 2, train_cost: 2 },
  ],
};
