import type { Trip } from "./types";

/** Bundled trips — same order/IDs as `data/archive/trips.txt` seed. */
export const STATIC_TRIPS: Trip[] = [
  { id: 1, start: "Boston", end: "Miami", points: 12 },
  { id: 2, start: "Calgary", end: "Phoenix", points: 13 },
  { id: 3, start: "Calgary", end: "Salt-Lake-City", points: 7 },
  { id: 4, start: "Chicago", end: "New-Orleans", points: 7 },
  { id: 5, start: "Chicago", end: "Santa-Fe", points: 9 },
  { id: 6, start: "Dallas", end: "New-York", points: 11 },
  { id: 7, start: "Denver", end: "El-Paso", points: 4 },
  { id: 8, start: "Denver", end: "Pittsburgh", points: 11 },
  { id: 9, start: "Duluth", end: "El-Paso", points: 10 },
  { id: 10, start: "Duluth", end: "Houston", points: 8 },
  { id: 11, start: "Helena", end: "Los-Angeles", points: 8 },
  { id: 12, start: "Kansas-City", end: "Houston", points: 5 },
  { id: 13, start: "Los-Angeles", end: "Chicago", points: 16 },
  { id: 14, start: "Los-Angeles", end: "Miami", points: 20 },
  { id: 15, start: "Los-Angeles", end: "New-York", points: 21 },
  { id: 16, start: "Montreal", end: "Atlanta", points: 9 },
  { id: 17, start: "Montreal", end: "New-Orleans", points: 13 },
  { id: 18, start: "New-York", end: "Atlanta", points: 6 },
  { id: 19, start: "Portland", end: "Nashville", points: 17 },
  { id: 20, start: "Portland", end: "Phoenix", points: 11 },
  { id: 21, start: "San-Francisco", end: "Atlanta", points: 17 },
  { id: 22, start: "Sault-St-Marie", end: "Nashville", points: 8 },
  { id: 23, start: "Sault-St-Marie", end: "Oklahoma-City", points: 9 },
  { id: 24, start: "Seattle", end: "Los-Angeles", points: 9 },
  { id: 25, start: "Seattle", end: "New-York", points: 22 },
  { id: 26, start: "Toronto", end: "Miami", points: 10 },
  { id: 27, start: "Vancouver", end: "Montreal", points: 20 },
  { id: 28, start: "Vancouver", end: "Santa-Fe", points: 13 },
  { id: 29, start: "Winnipeg", end: "Houston", points: 12 },
  { id: 30, start: "Winnipeg", end: "Little-Rock", points: 11 },
];
